name: Run TradingViewNews Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install required packages for Puppeteer
        run: sudo apt-get update && sudo apt-get install -y libnss3 libxss1 libasound2t64

      - name: Run scraper
        run: node main.js